### ISSUE TITLE
npm package transfer of ownership

### ISSUE THREAD

**Issue by tecfu** [Jimmy02020/fmod#1]
Hi. Would you be willing to transfer the ownership of the npm package `fmod` to me? 

I have ported the c builtin function [fmod](https://en.cppreference.com/w/c/numeric/math/fmod) to javascript, and would like to use the `fmod` name on npm (since you don't appear to use or even want it). You could transfer the package as follows:

```
npm owner add npm tecfu fmod
npm owner rm jimmy02020 fmod
```

My username on npm is `tecfu`

Thanks!

**Comment by jalal246** [comment]
no
